name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./src/sales-management-api.sln

      - name: Build the solution
        run: dotnet build ./src/sales-management-api.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./src/Test/TestUntariosMSTest.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsMSTest.trx"

      - name: Run unit tests with report
        run: dotnet test ./src/Test/TestUnitariosNUnit.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsNUnit.trx"

      - name: Run unit tests with report
        run: dotnet test ./src/Test/TestUnitariosXUnit.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsXUnit.trx"
