name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Build the solution
        run: dotnet build ./UnitTests.sln --configuration Release --no-restore

      - name: Run unit tests in MSTest
        run: dotnet test ./UnitTestMSTest/UnitTestMSTest.csproj --configuration Release --no-build 

      - name: Run unit testsin in NUnit
        run: dotnet test ./UnitTestnUnit/UnitTestnUnit.csproj --configuration Release --no-build 

      - name: Run unit tests in XUni
        run: dotnet test ./UnitTestxUnit/UnitTestxUnit.csproj --configuration Release --no-build 
