name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build the solution
        run: dotnet build ./UnitTests.sln --configuration Release --no-restore -f net9.0

      - name: Run unit tests with report
        run: dotnet test ./UnitTestMSTest/TestUntariosMSTest.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsMSTest.trx"

      - name: Run unit tests with report
        run: dotnet test ./UnitTestNUnit/TestUnitariosNUnit.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsNUnit.trx"

      - name: Run unit tests with report
        run: dotnet test ./UnitTestXUnit/TestUnitariosXUnit.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResultsXUnit.trx"
